---
S3ToLocal:
  s3-profle: default
  files-to-download:
    - s3-bucket: mtp-data-files
      key: raw-data/v_11_18_ot_22_04_chop_11_1/associationByDatasourceDirect/part-00008-722b5d0f-0296-4d8c-8a67-bb3a5c9b25c7-c000.json
      type: file
      save-path: /Users/cheny39/Documents/work/tmp/tmp/
      overwrite: True
      checksum: 123
      checksum-type: md5
      checksum-matching: False
    - s3-bucket: mtp-data-files
      key: raw-data/v_11_18_ot_22_04_chop_11_1/associationByDatasourceDirect/
      type: dir
      save-path: /Users/cheny39/Documents/work/tmp/association/
      checksum-matching: True
      overwrite: True
steps:
  - S3ToLocal