---
FTPToLocal:
  host-name: ftp.ebi.ac.uk
  # if is_anonymous is false, user must provide username and pwd to connect to the ftp, that could be refers to prefect secretes.
  is-anonymous:  True
  overwrite: True
  is-sftp: False
  use-prefect-secret-block: False
  prefect-block-secret-pwd: ccdi-ftp-chop-pwd-yizhen
  prefect-block-secret-username: ccdi-ftp-chop-username-yizhen
  #type : MD5, SHA-1 , SHA-2
  checksum-type: SHA-1
  checksum-matching: True
  # Type can be file or dir.
  # If type is dir, the program will download all the files with ftp folder WITHOUT checksum validation.
  # if type is dir, you need to provide folder path in files to download
  # if type is file
  # you have the option to validate each file's checksum
  # you have to list all the files to be downloaded
  type: file
  # set file_extension as n/a, then will skip file extension match
  file-extension: json
  save-path: /home/cheny39/tmp/
  files-to-download:
    - path: pub/databases/opentargets/platform/23.02/output/etl/json/targets/part-00156-a58b02a9-0daa-4cf0-aac3-20428ba520c2-c000.json
      checksum: 385099f668c52ea9cfcec76d81a9f6da8aa10d0e
    - path: pub/databases/opentargets/platform/23.02/output/etl/json/targets/part-00049-a58b02a9-0daa-4cf0-aac3-20428ba520c2-c000.json
      checksum: bb81e0a25227b3fa8219969addda90eacee951fa
steps:
  - FTPToLocal
