---
S3ToLocal:
  s3-profile: mtp-opensearch
  save-path: /Users/cheny39/Documents/work/tmp/tmp/
  overwrite: True
  checksum-type: md5
  checksum-matching: True
  s3-bucket: d3b-openaccess-us-east-1-prd-pbta
  type: file
  files-to-download:
    - key: open-targets/v12/mtp-tables/pre-release/putative-oncogene-fused-gene-freq.jsonl.gz
      checksum: 123
steps:
  - S3ToLocal
